on: pull_request

jobs:
  deploy_url:
    runs-on: ubuntu-latest
    name: Print the preview url

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1

        with:
          message: If all goes well this PR will be deployed and viewable at https://pr-${{github.event.number}}-dot-staging-dot-celo-org-website.uc.r.appspot.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}